### ISSUE TITLE
http error 401 after sending same url a second time

### ISSUE THREAD

**Issue by draaw** [SiLeBAT/mibi-portal-server#23] opened 2018-03-21 08:06 UTC
As a portal user I want to enter the actual url again and receive the same result as before

Example: upload and validate a file (POST). Your url will be: https://epilab.bfr.berlin/validate. Then enter the url again (GET) and you will get the 401 error

**Comment by birgitlewicki** [comment] 2018-04-11 09:52
Duplicate of #21

**Closed** 2018-04-11 09:52 UTC
Labels: Bug, Duplicate
