### ISSUE TITLE
Register / login: The case of the letters of the email address should be irrelevant

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/mibi-portal-server#33] opened 2018-06-05 13:35 UTC
If you register with Abcd.Efgh@bla.de and then try to login with abcd.efgh@bla.de it is not possible. Only Abcd.Efgh@bla.de (with 2 capital letters) is successful. It should be possible to login without having to remember the case of the letters. The case should be ignored.

**Comment by birgitlewicki** [comment] 2018-06-05 16:51
Duplicate of #32 
Closing

**Closed by birgitlewicki** 2018-06-05 16:51 UTC
Labels: Bug
